module.exports = {
	content: ["./src/**/*.{js,jsx,ts,tsx}"],
	theme: {
		colors: {
			transparent: "transparent",
			current: "currentColor",
			white: "#ffffff",
			purple: "#3f3cbb",
			midnight: "#121063",
			metal: "#565584",
			tahiti: "#3ab7bf",
			silver: "#ecebff",
			"bubble-gum": "#ff77e9",
			bermuda: "#78dcca",
			first: "#1C1D22",
			secc: "#313B44",
			third: "#606467",
			text: "#AAA8AD",
			accent1: "#FF4F00",
			accent2: "#EF6817",
		},
		extend: {},
	},
	plugins: [],
};
